clinic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('practitioners/', include('practitioners.urls')),
    path('visitors/', include('visitors.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('', views.home, name='home'),
    path('practitioners', views.practitioners, name='practitioners'),
    path('visitors', views.visitors, name='visitors'),
    path('signup', views.handleSignup, name='handleSignup'),
    path('login', views.handlelogin, name='handlelogin'),
    path('logout', views.handlelogout, name='handlelogout')
]

practitioners/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('', views.practitioners, name='practitioners'),
    path("practitioners/", views.practitioners, name="practitioners"),
    path("add_practitioners/", views.add_practitioners, name="add_practitioners"),
    path("practitioners_details/<int:id>/", views.practitioners_details, name="practitioners_details"),
    path("edit_practitioners/<int:id>/", views.add_practitioners, name="edit_spractitioners"),
    
]

visitors/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('', views.visitors, name='visitors')
    
]

home/models.py
from django.db import models

# Create your models here.

practitioners/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
GENDER_CHOICES = (
    ("Male", "Male"),
    ("Female", "Female"),
)
SHIFT_CHOICES = (
    ("Day", "Day"),
    ("Night", "Night"),
)
STAFF_CHOICES = (
    ("Nurse", "Nurse"),
    ("Clinical Officer", "Clinical Officer"),
    ("Public Health Officer", "Public Health Officer"),
    ("Cleaner", "Cleaner"),
    ("Security", "Security"),
    ("Driver", "Driver"),
    ("Counselor", "Counselor"),
    ("Nutritionist", "Nutritionist"),
)

class BaseInfo(models.Model):
    id_number = models.CharField(max_length=200, unique=True)
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    phone = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    

    class Meta:
        abstract = True


class Practitioners(BaseInfo):
    position = models.CharField(max_length=100, choices=STAFF_CHOICES)
    employment_date = models.DateTimeField()
    shift = models.CharField(max_length=20, choices=SHIFT_CHOICES)

    def __str__(self):
        return self.name

visitors/models.py
from django.db import models

# Create your models here.

practitioners/forms.py
from django import forms
from . models import Practitioners





class PractitionersForm(forms.ModelForm):
    class Meta:
        model = Practitioners
        fields = ('__all__')

home/views.py
from django.shortcuts import render, HttpResponse, redirect

from django.contrib import messages
from django.contrib.auth  import authenticate,  login, logout
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

def practitioners(request):
    return render(request, 'practitioners/practitioners.html')
def visitors(request):
    return render(request, 'visitors/visitors.html')


def handleSignup(request):
    if request.method=="POST":
        # Get the post parameters
        username=request.POST['username']
        email=request.POST['email']
        fname=request.POST['fname']
        lname=request.POST['lname']
        pass1=request.POST['pass1']
        pass2=request.POST['pass2']

        # check for errorneous input
        if len(username)>10:
            messages.error(request, " Your user name must be under 10 characters")
            return redirect('home')

        if not username.isalnum():
            messages.error(request, " User name should only contain letters and numbers")
            return redirect('home')
        if (pass1!= pass2):
             messages.error(request, " Passwords do not match")
             return redirect('home')
        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name= fname
        myuser.last_name= lname
        myuser.save()
        messages.success(request, " Your Portal has been successfully created")
        return redirect('home')

    else:
        return HttpResponse("404 - Not found")

def handlelogin(request):
     if request.method=="POST":
        # Get the post parameters
        loginusername=request.POST['loginusername']
        loginpassword=request.POST['loginpassword']

        user=authenticate(username= loginusername, password= loginpassword)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("home")
        else:
            messages.error(request, "Invalid credentials! Please try again")
            return redirect("home")
     return HttpResponse('handlelogin')
     return HttpResponse("404 - Not found")

def handlelogout(request):
       logout(request)
       messages.success(request,"successfully logged out")
       return redirect('home')
       return HttpResponse('handlelogout')

practitioners/views.py
from django.shortcuts import render, HttpResponse, redirect
from . models import Practitioners
from . forms import PractitionersForm

# Create your views here.
def practitioners(request):
    return render(request, 'practitioners/practitioners.html')

def practitioners(request):
    practitioners = Practitioners.objects.all()
    return render(request, "practitioners/practitioners.html", {"practitioners": practitioners})
def practitioners_details(request, id):
    practitioners = Practitioners.objects.get(pk=id)
    context = {
        "practitioners": practitioners
    }
    return render(request, "data/practitioners_details.html", context)

def add_practitioners(request, id=0):
    if request.method == "GET":
        if id == 0:
            form = PractitionersForm()
        else:
            practitioners = Practitioners.objects.get(pk=id)
            form = PractitionersForm(instance=practitioners)
        return render(request, "practitioners/add_practitioners.html", {"form": form})
    else:
        if id == 0:
            form = PractitionersForm(request.POST)
        else:
            practitioners = Practitioners.objects.get(pk=id)
            form = PractitionersForm(request.POST, instance=practitioners)
        if form.is_valid():
            form.save()
        return redirect('practitioners')

visitors/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def visitors(request):
    return render(request, 'visitors/visitors.html')

templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>{% block title %}{% endblock title %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Portal</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="/practitioners">Practitioners</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/visitors">Visitors</a>
          </li>
          

        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

{% if user.is_authenticated %}
 <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
  <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Welcome
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/logout">Logout</a></li>
            
          </ul>
    </li>
</ul>
 {{request.user}}
{% else %}
      <!-- Button trigger SignUp modal -->
<button type="button" class="btn btn-success mx-2" data-bs-toggle="modal" data-bs-target="#signupModal">
  signup
</button>
        
             <!-- Button trigger Login modal -->
<button type="button" class="btn btn-success mx-2" data-bs-toggle="modal" data-bs-target="#loginModal">
  Login
</button>


{% endif %}       

      </div>
    </div>
  </nav>
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message</strong> {{ message.tags }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

  {% endfor %}


<!-- SignUp upModal -->
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signupModal">Sign Up</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <form action="/signup" method='post'>
      <div class="mb-3">
  <label for="username" class="form-label">Username</label>
  <input type="text" class="form-control" id="username" name="username" placeholder="choose a unique username" required>
</div> 
      <div class="mb-3">
  <label for="fname" class="form-label">First Name</label>
  <input type="text" class="form-control" id="fname" name="fname" placeholder="First Name" required>
</div> 
      <div class="mb-3">
  <label for="lname" class="form-label">Last Name</label>
  <input type="text" class="form-control" id="lname" name="lname" placeholder="Last Name" required>
</div> 
      <div class="mb-3">
  <label for="email" class="form-label">Email address</label>
  <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
</div>
      <div class="mb-3">
  <label for="pass1" class="form-label">Password</label>
  <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Enter a password" required>
</div>
      <div class="mb-3">
  <label for="pass2" class="form-label">Confirm Password</label>
  <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Enter password again" required>
</div>
  
      </div>
      <div class="modal-footer">
         {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      </div>
    </div>
  </div>
</div>

<!-- Login upModal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModal">Log In</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       <form action="/login" method='post'>
      <div class="mb-3">
  <label for="username" class="form-label">Username</label>
  <input type="text" class="form-control" id="username" name="loginusername" placeholder="choose a unique username" required>
</div> 
     
      <div class="mb-3">
  <label for="pass" class="form-label">Password</label>
  <input type="password" class="form-control" id="pass" name="loginpassword" placeholder="Enter a password" required>
</div>
      
  
      </div>
      <div class="modal-footer">
         {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
  {% block body %}{% endblock body %}

  <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>


  {% block js %}{% endblock %}

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home/home.html
{% extends 'base.html' %}
{% block title %} home {% endblock title %}
{% block body %} 
    <div class="container-fluid" style="background-color: grey;">
        <div class="row">
            <div class="col-xl-4 col-md-6 mt-5">
                <div class="card text-white mb-4" style="background-color: red;">
                    <div class="card-body">
                        <h4>Practitioners</h4>
                        </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white btn btn-primary stretched-link" href="{% url 'practitioners' %}">Details</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
     <div class="col-xl-4 col-md-6 mt-5">
                <div class="card text-white mb-4" style="background-color: green;">
                    <div class="card-body">
                        <h4>Visitors</h4>
                        </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white btn btn-primary stretched-link" href="{% url 'visitors' %}">Details</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
      <footer class="footer mt-auto py-3" style="background-color: darkblue;">
  <div class="container">
      <code>
          <h5 class="text-center text-white">Clinic Management System 2021</h5>
      </code>

  </div>
</footer>
     

{% endblock body %}

templates/practitioners/add_practitioners.html
{% extends 'base.html' %}
{% block title %} practitioners {% endblock title %}
{% block body %}  <div class="container">
<h2>Practitioners</h2>

    

<div class="container">
        <div class="row">
            <div class="col-4 mt-5 mx-auto">
            <a href="/" class="btn btn-secondary">Back Home</a>
        </div>
        <div class="col-4 mt-5 mx-auto">
            <a href="{% url 'practitioners' %}" class="btn btn-warning">Back To Clinic Staff</a>
        </div>
        </div>
        <div class="col-md-12 mt-5">
            <div class="jumbotron">
                <h4 class="display-4 text-center">Add New Staff Member</h4>
                <form action="" method="post">
                    {% csrf_token %}
                   
                    

</head>
<body class="">
<div class="container-fluid mt-5 mx-auto" style="background-color: skyblue;">
      <center><nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: darkblue;">
      <a class="navbar-brand" href="/">CLINIC MANAGEMENT SYSTEM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
</center>
    
    
    
  
                    

<div id="div_id_id_number" class="form-group"> <label for="id_id_number" class=" requiredField">
                Id number<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="id_number" maxlength="200" class="textinput textInput form-control" required id="id_id_number"> </div> </div> <div id="div_id_name" class="form-group"> <label for="id_name" class=" requiredField">
                Name<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="name" maxlength="200" class="textinput textInput form-control" required id="id_name"> </div> </div> <div id="div_id_gender" class="form-group"> <label for="id_gender" class=" requiredField">
                Gender<span class="asteriskField">*</span> </label> <div class=""> <select name="gender" class="select form-control" required id="id_gender"> <option value="" selected>---------</option> <option value="Male">Male</option> <option value="Female">Female</option>

</select> </div> </div> <div id="div_id_phone" class="form-group"> <label for="id_phone" class=" requiredField">
                Phone<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="phone" maxlength="200" class="textinput textInput form-control" required id="id_phone"> </div> </div> <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
                Email<span class="asteriskField">*</span> </label> <div class=""> <input type="email" name="email" maxlength="200" class="emailinput form-control" required id="id_email"> </div> </div> <div id="div_id_position" class="form-group"> <label for="id_position" class=" requiredField">
                Position<span class="asteriskField">*</span> </label> <div class=""> <select name="position" class="select form-control" required id="id_position"> <option value="" selected>---------</option> <option value="Nurse">Nurse</option> <option value="Clinical Officer">Clinical Officer</option> <option value="Public Health Officer">Public Health Officer</option> <option value="Cleaner">Cleaner</option> <option value="Security">Security</option> <option value="Driver">Driver</option> <option value="Counselor">Counselor</option> <option value="Nutritionist">Nutritionist</option>

</select> </div> </div> <div id="div_id_employment_date" class="form-group"> <label for="id_employment_date" class=" requiredField">
                Employment date<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="employment_date" class="datetimeinput form-control" required id="id_employment_date"> </div> </div> <div id="div_id_shift" class="form-group"> <label for="id_shift" class=" requiredField">
                Shift<span class="asteriskField">*</span> </label> <div class=""> <select name="shift" class="select form-control" required id="id_shift"> <option value="" selected>---------</option> <option value="Day">Day</option> <option value="Night">Night</option>

</select> </div> </div>

                    
                    
                    </div>
                </form>
                
            </div>
        </div>
    </div>
    

</div>
    
                    <br>
                    <div class="row">
                        <div class="col-md-8">
                           <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        <div class="col-md-4">
                            <a href="{% url 'practitioners' %}" class="btn btn-secondary btn-block btn-lg">
                                Back to Staff Members
                            </a>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
    </div>

   <div class="col-auto d-none d-lg-block">
          
        </div>     
      </div>
{% endblock body %}

     

templates/practitioners/practitioners.html
{% extends 'base.html' %}
{% block title %} practitioners {% endblock title %}
{% block body %}  <div class="container">
<h2>Practitioners</h2>

    
{% block heading %}  
<div class="container" style="background-color: rgb(231, 221, 221);">
    <div class="row mx-auto">
        <div class="col-4 mt-5 mx-auto">
            <h1>Staff Members</h1>
        </div>
        <div class="col-4 mt-5 mx-auto">
            <a href="{% url 'add_practitioners' %}" class="btn btn-primary">Add Staff Member</a>
        </div>
        <div class="col-4 mt-5 mx-auto">
            <a href="/" class="btn btn-secondary">Back Home</a>
        </div>
    </div>
</div>
{% endblock heading %}
<hr>

<hr class="height-3">
<div class="container" style="background-color: rgb(231, 221, 221);">
 <table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Staff Name</td>
            <td>Position</td>
            <td>Date Employed</td>
            <td>Edit</td>
            <td>Delete</td>
            <td>Details</td>
        </tr>
    </thead>
    <tbody>
        {% for staff in staffs %}
           <tr>
               <td>{{ practitioners.name }}</td>
               <td>{{ practitioners.position }}</td>
               <td>{{ practitioners.employment_date }}</td>
               <td><a href="{% url 'edit_staff' staff.id %}" class="btn btn-success">Edit</a></td>
               <td><a href="#" class="btn btn-danger">Delete</a></td>
               <td><a href="{% url 'practitioners_details' staff.id %}" class="btn btn-primary">Details</a></td>
           </tr>
        {% endfor %}
    </tbody>
</table>
</div>

   <div class="col-auto d-none d-lg-block">
          
        </div>     
      </div>{% endblock body %}

     

templates/practitioners/practitioners_details.html
{% extends 'base.html' %}
{% block title %} practitioners {% endblock title %}
{% block body %}  <div class="container">
<h2>Practitioners</h2>

    
{% block heading %}  
<div class="container">
    <div class="row">
        <div class="col-md-8 mt-5 mx-auto" style="background-color: rgb(231, 221, 221);">
            <code>
            <h3 class="text-center m-3"><i>Staff Profile</i></h3>
            </code>
            <h4 class="text-center">Staff Name: {{ staff.name }}</h4>
            <h6 class="text-center">ID Number: {{ staff.id_number }}</h6>
            <h6 class="text-center">Phone Number: {{ staff.phone }}</h6>
            <h6 class="text-center">Email Address: {{ staff.email }}</h6>
            <h6 class="text-center">Gender: {{ staff.gender }}</h6>
            <h6 class="text-center">Position: {{ staff.position }}</h6>
            <h6 class="text-center">Employment Date: {{ staff.employment_date }}</h6>
            <h6 class="text-center">Shift: {{ staff.shift }}</h6>
            <hr>

            <div class="row mx-auto">
            <div class="col-4 mt-5 mx-auto m-5">
                <a href="{% url 'practitioners' %}" class="btn btn-secondary">Back To Staff Members</a>
            </div>
            <div class="col-4 mt-5 mx-auto m-5">
                <a href="{% url 'add_practitioners' %}" class="btn btn-secondary">Add New Staff</a>
            </div>
            <div class="col-4 mt-5 mx-auto m-5">
                <a href="/" class="btn btn-secondary">Back Home</a>
            </div>
        </div>
        </div>
    </div>
</div>
  

   <div class="col-auto d-none d-lg-block">
          
        </div>     
      </div>{% endblock body %}

     

templates/visitors/visitors.html
{% extends 'base.html' %}
{% block title %} visitors {% endblock title %}
{% block body %}  <div class="container">
<h2>Visitors</h2>

     

   <div class="col-auto d-none d-lg-block">
          
        </div>     
      </div>{% endblock body %}

     